In [1]:
import numpy as np
import pandas as pd

In [4]:
N = 100
df = pd.DataFrame(np.random.standard_normal((N,N)))
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-1.155130,-1.669566,-0.105023,0.386156,1.330495,0.252783,-0.925760,-0.502316,-0.695405,-1.760397,...,0.005031,1.346473,-0.765912,0.684320,0.880631,-0.413480,-0.859917,1.262685,2.300340,-0.259064
1,0.239265,0.343898,2.667985,0.788619,0.643656,-0.897550,-0.351867,-0.231961,-1.396724,0.259655,...,0.108048,-0.901644,0.811447,0.660400,-0.293120,-0.171035,-0.044349,-1.344261,0.273508,0.993112
2,-0.633718,-0.839441,1.369071,0.100113,0.889205,0.070035,-1.122517,0.575596,0.783135,-1.911305,...,-0.859733,-1.257264,1.359523,-0.935423,1.049514,-0.520644,-0.183435,-0.978583,0.180375,-1.181340
3,1.137638,0.557256,0.069853,0.758586,-1.299958,-0.849192,-0.571705,-0.521082,2.026986,-2.557242,...,-0.361183,-0.062426,-0.081791,-1.233861,1.079496,-1.091852,3.419964,-0.273600,0.635746,0.398180
4,-0.296589,0.702925,0.605357,0.194530,-0.762180,0.998382,1.016517,-0.179743,-0.442248,-1.241237,...,1.211361,0.140100,-1.016217,-1.429587,1.829894,-1.950609,-0.347593,0.184980,-0.701002,0.702768

In [5]:
def squarePandas(df):
    return df**2
def squareNumpy(df):
    return pd.DataFrame(df.values**2,index=df.index,columns=df.columns)

pd.testing.assert_frame_equal(squarePandas(df),squareNumpy(df))

In [6]:
%timeit -n 1 -r 5 squarePandas(df=df)

223 µs ± 83.6 µs per loop (mean ± std. dev. of 5 runs, 1 loop each)

In [7]:
%timeit -n 1 -r 5 squareNumpy(df=df)

158 µs ± 48.3 µs per loop (mean ± std. dev. of 5 runs, 1 loop each)